#
# This file is part of Edgehog.
#
# Copyright 2021 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build and Test Backend

on:
  # Run when pushing to stable branches
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/backend-test.yaml'
    branches:
    - 'master'
  # Run on pull requests matching apps
  pull_request:
    paths:
    - 'backend/**'
    - '.github/workflows/backend-test.yaml'

env:
  elixir_version: "1.12.3"
  otp_version: "24.1"
jobs:
  test-coverage:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: backend/deps
        key: ${{ runner.os }}-deps-${{ env.otp_version }}-${{ env.elixir_version }}-${{ hashFiles(format('{0}{1}{2}', github.workspace, '/backend/', '/mix.lock')) }}
    - uses: actions/cache@v1
      with:
        path: backend/_build
        key: ${{ runner.os }}-_build-${{ env.otp_version }}-${{ env.elixir_version }}
    - uses: erlef/setup-elixir@v1.6.0
      with:
        otp-version: ${{ env.otp_version }}
        elixir-version: ${{ env.elixir_version }}
    - name: Install Dependencies
      working-directory: backend
      run: mix deps.get
    - name: Check formatting
      working-directory: backend
      run: mix format --check-formatted
    - name: Compile
      working-directory: backend
      run: mix do compile
    - name: Test
      working-directory: backend
      run: mix coveralls.github --exclude wip -o coverage_results
